language: generic
sudo: required
services:
  - docker  
  
before_install:
  - docker build -t majiedahamed/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true majiedahamed/docker-react npm run test
